import {
  BranchesSchema,
  ChangePassSchema,
  DiagnoseSchema,
  DoctorSigninSchema,
  FamilyMemberSchema,
  FeedbackSchema,
  PatientForgotPasswordSchema,
  QueueSchema,
  RegisterForQueueSchema,
  ServicesSchema,
  SigninSchema,
  SignupSchema,
  StaffSchema,
  UpdateProfileSchema,
  VerificationCodeSchema,
  VerificationRejectSchema,
} from "./schema";

export {
  BranchesSchema,
  ChangePassSchema,
  DiagnoseSchema,
  DoctorSigninSchema,
  FamilyMemberSchema,
  FeedbackSchema,
  PatientForgotPasswordSchema,
  QueueSchema,
  RegisterForQueueSchema,
  ServicesSchema,
  SigninSchema,
  SignupSchema,
  StaffSchema,
  UpdateProfileSchema,
  VerificationCodeSchema,
  VerificationRejectSchema,
};
